### PR TITLE
init the si1145 & changed the mqtt config

### PR DESCRIPTION
**Pull request by tkoeberl**
si1145 did not work for me. only works with the uv.begin.
I only wanted to used MQTT. Made that possible.

### CODE REVIEW

**Comment by jhughes1010** [comment]
Just looked at the code changes and they make sense. Thanks for the submission.

I’m in the middle of moving and it will be 10wks before I’ll be back to a point for full testing and validation, but visual inspection makes sense!

James

From: tkoeberl ***@***.***>
Date: Saturday, January 22, 2022 at 2:19 PM
To: jhughes1010/weather ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)

si1145 did not work for me. only works with the uv.begin.
I only wanted to used MQTT. Made that possible.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/jhughes1010/weather/pull/9

Commit Summary

  *   240b73e<https://github.com/jhughes1010/weather/pull/9/commits/240b73e404a73a9308f8db6c6f2552033152a089> Added uv.begin() to make it work
  *   33d31e0<https://github.com/jhughes1010/weather/pull/9/commits/33d31e0a98eb1e3807977586d7e46127c9303650> made MQTT the same config style
  *   5dd5603<https://github.com/jhughes1010/weather/pull/9/commits/5dd5603244e596a7eaa84b4af6d2dd43d2bd7c1a> tuned .gitignore

File Changes

(5 files<https://github.com/jhughes1010/weather/pull/9/files>)

  *   M .gitignore<https://github.com/jhughes1010/weather/pull/9/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (1)
  *   M iot_data.ino<https://github.com/jhughes1010/weather/pull/9/files#diff-3d46adcf3194a7ed93469a577bcecd3b0e9ac5e155f4736129e04ab2d207961c> (3)
  *   M sensors.ino<https://github.com/jhughes1010/weather/pull/9/files#diff-31767c6753d36a2a162cc65f79a3ac40c428aa953d6349182ec2a3797f251a14> (14)
  *   M weather.ino<https://github.com/jhughes1010/weather/pull/9/files#diff-e3ba6b048e6a0e1cb844041f9b733ba25528187b740b2b32f1df29e2c9dbc04f> (6)
  *   M wifi.ino<https://github.com/jhughes1010/weather/pull/9/files#diff-71cd251dca890c7a40d8da2110241ae5009f6071abb445de451d4c7fd35a9cf2> (11)

Patch Links:

  *   https://github.com/jhughes1010/weather/pull/9.patch
  *   https://github.com/jhughes1010/weather/pull/9.diff

**Comment by tkoeberl** [comment]
I added an commit to return -1 if no SI1145 is attached. Makes more sense ;)

**Review by jhughes1010 — APPROVED** [review]

**Comment by jhughes1010** [comment]
Pull request approved

**Comment by jhughes1010** [comment]
I approved the pull request. Called is v1.2.2

James Hughes

**Comment by tkoeberl** [comment]
Hi,

 

already have seen it. But work consumes a lot of time right now.

 

 Thanks a lot :D

 

 
 

Gesendet: Mittwoch, 06. April 2022 um 16:08 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)


 
I approved the pull request. Called is v1.2.2

James Hughes

**Comment by tkoeberl** [comment]
Hi James,

 

again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )

 
 

Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)


 
No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by jhughes1010** [comment]
Where are you located, if I might ask?

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by jhughes1010** [comment]
Glad it’s useful to you! 😉

I’m starting to look at the wind speed and top wind speed we can accurately measure now. Compressed can air only gets me to 30km/h, but the sample math all makes sense at that speed.

V1.3.1 includes enhancement to bail and go to sleep (vs. trip WDT and reboot)when no wifi is present.

Are you in Europe or Germany by chance? My friend, Thomas Krebs (PCB collaborator on deep sleep design), has gone silent since January. He had covid and was out of the hospital, but that’s the last I’ve heard from him. I’m looking for someone that could more easily phone his business number and see if he is well.

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by tkoeberl** [comment]
Hi James,Germany, Bavaria, Beilngries. Am 08.04.2022 12:39 schrieb James Hughes ***@***.***>:

Where are you located, if I might ask?







James







From: tkoeberl ***@***.***>



Date: Wednesday, April 6, 2022 at 11:46 AM



To: jhughes1010/weather ***@***.***>



Cc: James Hughes ***@***.***>, State change ***@***.***>



Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



Hi James,















again, thanks a lot for you effort in this project.







Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.







As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )



















Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr



Von: "James Hughes" ***@***.***>



An: "jhughes1010/weather" ***@***.***>



Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>



Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)















No action needed. Just letting you know that I finally dealt with your pull request :)







James Hughes

**Comment by tkoeberl** [comment]
Hi,

 

looks like I need to upgrade the firmware :D

 

Yes I'm based in Germany. Whats the company, maybe I can find out something.

Thomas Krebs is a usual name. Like Ryan Miller ;) Not easy to filter out all the false positives ;)

 
 

Gesendet: Dienstag, 11. Oktober 2022 um 10:01 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)


 
Glad it’s useful to you! 😉

I’m starting to look at the wind speed and top wind speed we can accurately measure now. Compressed can air only gets me to 30km/h, but the sample math all makes sense at that speed.

V1.3.1 includes enhancement to bail and go to sleep (vs. trip WDT and reboot)when no wifi is present.

Are you in Europe or Germany by chance? My friend, Thomas Krebs (PCB collaborator on deep sleep design), has gone silent since January. He had covid and was out of the hospital, but that’s the last I’ve heard from him. I’m looking for someone that could more easily phone his business number and see if he is well.

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by jhughes1010** [comment]
I’ve heard from Thomas. His mail suddenly started going to spam, still not sure why.

James

From: tkoeberl ***@***.***>
Reply-To: jhughes1010/weather ***@***.***>
Date: Tuesday, October 11, 2022 at 4:03 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)

Hi,



looks like I need to upgrade the firmware :D



Yes I'm based in Germany. Whats the company, maybe I can find out something.

Thomas Krebs is a usual name. Like Ryan Miller ;) Not easy to filter out all the false positives ;)




Gesendet: Dienstag, 11. Oktober 2022 um 10:01 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



Glad it’s useful to you! 😉

I’m starting to look at the wind speed and top wind speed we can accurately measure now. Compressed can air only gets me to 30km/h, but the sample math all makes sense at that speed.

V1.3.1 includes enhancement to bail and go to sleep (vs. trip WDT and reboot)when no wifi is present.

Are you in Europe or Germany by chance? My friend, Thomas Krebs (PCB collaborator on deep sleep design), has gone silent since January. He had covid and was out of the hospital, but that’s the last I’ve heard from him. I’m looking for someone that could more easily phone his business number and see if he is well.

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by jhughes1010** [comment]
If your WiFi is spotty or poor for the distance to the station. I’ve started coding the software for a v4 version (LoRa radio version) from Debasish who reached out for collaboration. Station can be several km from home. I live on a property now where my station is >100m from WiFi and it is no longer an option. LoRa radio makes perfect sense.

James

From: tkoeberl ***@***.***>
Reply-To: jhughes1010/weather ***@***.***>
Date: Tuesday, October 11, 2022 at 4:03 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)

Hi,



looks like I need to upgrade the firmware :D



Yes I'm based in Germany. Whats the company, maybe I can find out something.

Thomas Krebs is a usual name. Like Ryan Miller ;) Not easy to filter out all the false positives ;)




Gesendet: Dienstag, 11. Oktober 2022 um 10:01 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



Glad it’s useful to you! 😉

I’m starting to look at the wind speed and top wind speed we can accurately measure now. Compressed can air only gets me to 30km/h, but the sample math all makes sense at that speed.

V1.3.1 includes enhancement to bail and go to sleep (vs. trip WDT and reboot)when no wifi is present.

Are you in Europe or Germany by chance? My friend, Thomas Krebs (PCB collaborator on deep sleep design), has gone silent since January. He had covid and was out of the hospital, but that’s the last I’ve heard from him. I’m looking for someone that could more easily phone his business number and see if he is well.

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Comment by tkoeberl** [comment]
upsi :D


 

Gesendet: Dienstag, 11. Oktober 2022 um 12:22 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)


 
I’ve heard from Thomas. His mail suddenly started going to spam, still not sure why.

James

From: tkoeberl ***@***.***>
Reply-To: jhughes1010/weather ***@***.***>
Date: Tuesday, October 11, 2022 at 4:03 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)

Hi,



looks like I need to upgrade the firmware :D



Yes I'm based in Germany. Whats the company, maybe I can find out something.

Thomas Krebs is a usual name. Like Ryan Miller ;) Not easy to filter out all the false positives ;)




Gesendet: Dienstag, 11. Oktober 2022 um 10:01 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



Glad it’s useful to you! 😉

I’m starting to look at the wind speed and top wind speed we can accurately measure now. Compressed can air only gets me to 30km/h, but the sample math all makes sense at that speed.

V1.3.1 includes enhancement to bail and go to sleep (vs. trip WDT and reboot)when no wifi is present.

Are you in Europe or Germany by chance? My friend, Thomas Krebs (PCB collaborator on deep sleep design), has gone silent since January. He had covid and was out of the hospital, but that’s the last I’ve heard from him. I’m looking for someone that could more easily phone his business number and see if he is well.

James

From: tkoeberl ***@***.***>
Date: Wednesday, April 6, 2022 at 11:46 AM
To: jhughes1010/weather ***@***.***>
Cc: James Hughes ***@***.***>, State change ***@***.***>
Subject: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)
Hi James,



again, thanks a lot for you effort in this project.

Thanks to you I can automatically close the shutter if it is to bright and I'm working with the window in the backgound.

As always: automation is not needed but helpful. (The switch to do this manually is 30cm away. :) )




Gesendet: Mittwoch, 06. April 2022 um 18:40 Uhr
Von: "James Hughes" ***@***.***>
An: "jhughes1010/weather" ***@***.***>
Cc: "tkoeberl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jhughes1010/weather] init the si1145 & changed the mqtt config (PR #9)



No action needed. Just letting you know that I finally dealt with your pull request :)

James Hughes

**Pull request merged**
